### ISSUE TITLE
请问一下使用壶类如何进行判定

### ISSUE THREAD

**Issue by xianggelila177** [jsc723/ygo-calc#1]
首先先感谢您开发这款软件软件以方便使用
请问当我使用强贪，金满，金谦，该如何编辑？

**Comment by jsc6924** [comment]
release的压缩包里有一个program-test.yml可以参考，我这里改过后重新贴一下
```yaml
        qyou-tan-tubo:
            count: 1
            description: '强贪壶'
            program: ['[1]/(> |D| 9);(# D.10 J);@;(# X B);(# D.2 H [draw])']
        qyou-kin-tubo:
            count: 1
            description: '强金壶'
            program: ['[^]@;(# X B);(# D.2 H [draw])']
        kin-ken-tubo:
            count: 1
            description: '金谦壶'
            program: 
                - '[1]/(> |D| 5);@;(# X B);(# D.6 T);
                    (if (> |T.a:rice-like| 0)
                        (# T.a:rice-like.1 H)
                        (if (> |T.a:kowakuma| 0) 
                            (# T.a:kowakuma.1 H) 
                            (# T.1 H)
                        )
                    );
                    (## T D);
                    (! "draw")'
        kotuchi:
            count: 2
            description: '万宝槌'
            program: ['(= x (- |H.!a:sushi| 1));/(> x 1);@;(# X B);(# H.!a:sushi D);(# D.:x H [draw])']
        munorengoku:
            count: 2
            description: '无之炼狱'
            program: ['/(> |H| 2);@;(# X B);(# D.1 H [draw])']
        tehuda-masatu:
            count: 1
            description: '手牌抹杀'
            program: ['@;(# X B);(= x |H|);(# H B);(# D.:x H [draw])']
        inochi-housatu:
            count: 2
            description: '削命'
            program: 
                - '[1](= x |H.a:mahou| );(= y |H.a:trap|);(= z (> |H.a:M| 0));(= k (+ x y z));(= h (- |H| k));/(< h 4);
                    @;(# X B);(= t (- 4 h));(# D.:t H [draw])'
        cup-of-ace:
            count: 2
            description: '圣杯A'
            program: ['@;(# X B);/(> (rand 0 1) 0);(# D.2 H [draw])']
```
强贪和强金应该直接照抄就行了。金谦壶比较复杂，需要自己写挑卡的逻辑，而且还有个自肃（这个自肃上面这么写其实也不对，感觉还是只能用全局变量+条件语句）。
